[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']
solc = '0.8.19'
evm_version = 'paris'
remappings = [
    '@chainlink/contracts/=node_modules/@chainlink/contracts',
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
